version : '2'
services:
  mysqldb:
    image: yuxiqian/bookie-mysql:latest

    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: bookie
      MYSQL_USER: docker
      MYSQL_PASSWORD: 123456docker
    ports:
      - "3306:3306"
    container_name: mysqldb

  server:
    image: yuxiqian/bookie-server:latest
    ports:
      - "8080:8080"
    links:
      - mysqldb
    depends_on:
      - mysqldb
    command: >
      /bin/bash -c '
      while ! nc -z database 3306;
      do
        echo "wait for database";
        sleep 1;
      done;

      echo "database is ready!";
      echo "start web service here";
      '
    container_name: server